#! /bin/bash
echo Starting Titan Interrogate.

PORT=8009
APP=qa27
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"

echo Targeting: $APP on port $PORT

while [ -h "$SOURCE" ]
do 
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
echo Executing at: "$DIR"
python $DIR/assets/platform/run.py --app=$APP --port=$PORT --root=$DIR
exit 0
